arj03/ssb-browser-demo

- assets/noavatar.svg
- ui/profile.js
- ui/ssb-profile-link.js
- write-dist.js
This adds a graphic to be displayed when a user does not have an avatar specified, rather than just display an image error by not specifying an image at all.
> Add graphic for when there is no avatar specified

- npm-shrinkwrap.json
Since this happens automatically during build, I figure I might as well commit this and do a pull request so it stops showing up in git diffs.
> Bump the shrinkwrap version - happens automatically during build

- ui/connections.js
Display connections as profile links so when you connect to a pub, you can click on it and see who it's following and/or follow the pub.
> Add link to profile for each connection

- package.json
Fixes the error about invalid SPDX expression when running npm install.
> Fix license specifier in package.json

- css/main.css
- ui/ssb-msg.js
Adds the ability to react to posts.  Fixes #12.
The existing logic for dislikes didn't work.  This fixes the bugs in that, but it still seems like a weird way to do things - once someone unlikes a post, no votes of any kind will show for that post from that person again, even if they post another vote later.  Is that how it's supposed to work?
> Add support for reacting to posts

- ui/connections.js
Allows for ailing connections to be disconnected.  Turns out they were being disconnected, just not forgotten, so the scheduler would try to reconnect them again.  Fixes #24
> Forget connections when clicking Disconnect

- ui/channel.js
- ui/channels.js
> Nice. Some minor suggestions:
>
>Show the number of posts next to to the channel
>Fix so that #something is the same as something. I get a few of these ##something
>Maybe sort it by the number of posts
>This could have a recent or something like that, that only looks at the latest 1000 post messages or so
>Anyway excellent work! Really happy to see you productive with the jitdb api.
From #43 by @arj03 
Only difference is that I tried 1000 post messages for "recently popular", and it resulted in a still-massive list, so I limited that down to 500.  Feel free to change it if you'd like, though.
> Implement Channels suggestions from arj03

- browser.html
- css/main.css
- defaultprefs.json
- localprefs.js
- npm-shrinkwrap.json
- package.json
- ui/browser.js
- ui/settings.js
This adds a basic settings screen with the following options:
* App/tab title (so it can be set to something other than "SSB browser demo").  This changes the tab title so different instances (different private windows for testing, etc.) can be easier identified.
* Number of hops to replicate.
* Caps key.
This ended up being a more difficult change than I expected.  It took me quite a while to figure out that ssb-browser-core had to be pulled in via require() instead of by its browser.js file being packaged into the included bundle.  This also required a bump to the browserify version because it was pulling in an ancient version of path-browserify which was breaking a whole bunch of stuff.
> Add basic Settings screen

- ui/public.js
Adds a filter for showing only messages from people you're directly following.  Also makes a few other changes:
* Adds a fieldset around filters.
* Adds labels for them so the text is clickable
* Shows a message if there are no messages to display, like if they've all been filtered out.
* Fixes bug where if no messages were found by a query (like if you filtered out everything in that page), you could not load more messages.
* Pagination was inconsistent.  Description said 50 messages, but queries were for 25.
* Displays a message showing which messages are being pulled, so even if all messages are filtered out, you can still see it's looking further back in the timeline.
> Add filter for only showing only messages from people you're directly following

- defaultprefs.json
- localprefs.js
- ui/public.js
Pretty self-explanatory.  When the filter checkboxes are clicked, this saves their state to local preferences so that they default to that the next time the Public tab is loaded.
> Save Public tab message filters to preferences so they are preserved

- ui/new-public-messages.js
- ui/public.js
Also fixes #55 and makes it so that if the "new public message(s)" indicator in the top menu pops up and you click it while you're already on the Public tab, it refreshes the view rather than just re-rendering the existing set of messages.
> Add Refresh button for Public messages

- net.js
- ui/connected.js
Implements the missing SSB.connected() function and adds it back into the path for SSB.getOOO().  This actually seems to work quite well - tested by loading a thread with a message outside of my graph, refreshing the page, and clicking "Get msg" before it connected.  It dutifully waited for the connection and then loaded the message.
Fixes #38.
> Implement SSB.connected() using events

- ui/connections.js
This makes it so if a user tries to use a "net:"-based invite, it displays a message explaining that it won't work and why.  It also adds the connection type next to each connection and places each on on its own line instead of relying on the browser to wrap them where we want.
> Disallow net: invites

- net.js
- ui/profile.js
This adds a new function SSB.connectedWithData() to register a callback for when not only is a peer connected but it's also of a type which has data (not a room).
With this in place, Profile buttons were changed to enqueue their requests if no connection is available that has data.  This should fix #39.
(And I'm sorry the diff's rather large, but most of it's in the extra indentation on the Profile button handlers so they are registered as callbacks with proper indentation level.)
> Add new SSB.connectedWithData() function and fix profile buttons

- ui/profile.js
Clicking "Block and delete" on a profile now blocks them and deletes their messages.
Fixes #68.
> Delete messages when blocking a user

- css/main.css
- defaultprefs.json
- ui/browser.js
- ui/components.js
- ui/connections.js
- ui/onboarding-dialog.js
- ui/public.js
Instead of having two hardcoded connection defaults (the pub and room) buried in the Connections screen's code, this moves those defaults to the default preferences file.  Additionally, it gives them friendly names on the Connections screen (so people know what they're connecting to and that the two are different), gives them easy-to-use Connect buttons, and removes them from the "Possible connections" list once you've connected to them.  Changing the add type dropdown on the form no longer resets the box's contents, which means if you paste an invite into the box before remembering to use the dropdown, you don't have to paste it again.
This also adds a new single-use onboarding GUI to make it easier for new users to get started.  It only pops up if the app was started without a key (so, …
> Onboarding improvements

- net.js
- ui/ssb-msg.js
When markdown contains a blob, rendering it tries to generate a link, but with no peer the URL is generated as an empty string, which causes an error.  This attempts to detect blobs in the body of messages and waits until we're connected to a peer with data to try to render them.
> Fix error caused by early Markdown rendering

- ui/ssb-msg.js
Fix typo that crept in with #75 and messed up waiting callbacks.
> Fix callback typo in Markdown rendering

- ui/channel.js
With this, you can open a Channel view (via Channels or clicking a channel link) and post a new message, and it will automatically be placed in that channel.  Also brings over a few of the other features from the Public tab, such as the ability to load more than 50 messages and the ability to refresh the feed.
Fixes #63
> Add ability to open Channel and post message

- net.js
I really don't like this solution, because it's yet another thing that depends on being connected to a peer with data.  But it was already dependent on it, so this doesn't change that.  It just fixes the following exception you'd get if you loaded up a Thread view in a new browser tab or refreshed while on a Thread view:
```
Uncaught (in promise) TypeError: Cannot read property 'partialReplication' of null
at Object.SSB.getThread (bundle-ui.js:137)
at bundle-ui.js:128730
at bundle-ui.js:114460
at bundle-ui.js:73648
at CollectStream._cb (bundle-ui.js:73601)
at CollectStream.end (bundle-ui.js:100318)
at FilterStream.ThroughStream.end (bundle-ui.js:100572)
at AsyncMapStream.end (bundle-ui.js:100458)
at ValueStream.resume (bundle-ui.js:100418)
at AsyncMapStream.ThroughStream.resume …
```
> Fix exception from Thread without connection

- ui/channel.js
- ui/public.js
When the browser is scrolled to the top, autorefresh the Public and Channel screens.  They refresh faster when there are no messages showing (such as when a new profile is first being set up and it's doing the initial sync), but then it refreshes every 30 seconds for as long as the browser is left scrolled to the top.  Once you scroll down, autorefresh is disabled.
> Autorefresh the Public and Channel screens

- css/public.css
- defaultprefs.json
- localprefs.js
- ui/channels.js
- ui/public.js
- ui/ssb-msg.js
Adds to #80 (so I could reuse the channel list functionality and only put that list together once) to allow for filtering the Public tab by favorite channels.  The channel list is saved separately from whether the filter is active or not so that you can add channels to the list and have them preserved across page loads regardless of whether you have the filter active.
This also fixes a bug where filter preferences were not being saved properly.
Also fixes an exception that could be thrown from ssb-msg if a message was not formatted properly and did not have content.
> Filter by favorite channels

- net.js
- ui/browser.js
- ui/private.js
- ui/profile.js
Adds a 'Send Message' button to Profile pages.  Also fixes issue with Private tab where if you refreshed the page while you were on the Private tab, it would not load the options for the Recipients list because it tried to do the query before being connected to a peer.
Fixes #61.
> Add 'Send Message' button to Profile pages

- ui/browser.js
If i18n has to use a fallback locale, this disables the warnings.  See https://github.com/arj03/ssb-browser-demo/pull/88#issuecomment-764677985
> Silence i18n fallback warnings

- messages.json
- ui/helpers.js
- ui/ssb-msg.js
Displays thread titles in ssb-msg, which means that "in reply to" now shows meaningful information about what they replied to.  Tries to load from cache first, and if it's not there, asynchronously requests the thread root be downloaded so it can display the thread title.
> Display thread titles in ssb-msg

- net.js
- ui/connections.js
- ui/private.js
- ui/ssb-msg.js
Adds a new SSB.getProfileNameAsync() function.  It works similarly to SSB.getProfileAsync(), except it only returns a name.  That way we can use other, possibly better and faster, ways of implementing that functionality.
I figure it's better to change things to the SSB plugins in one place rather than change each of them individually.
> Add SSB.getProfileNameAsync() so we can change implementation

- net.js
Evidently I had a typo in there.  I thought I had tested this.  Apparently I must not have cleared my cache properly.
> Fix typo in profile name function

- ui/public.js
Disable the autorefresh timer when the user navigates away from the Public tab.  Fixes #98.
> Stop the autorefresh timer when not on Public

- messages.json
- ui/private.js
Fixes issue where you could freeform type in a name into the Private Message recipient field and proceed to post a message without any complaints.
This pull request is based on my branch for Japanese language support (pull request #111) so I could add the error message in both English and Japanese (machine-translated).
Fixes #87.
> Private message validation

- css/public.css
- defaultprefs.json
- localprefs.js
- messages.json
- ui/public.js
If you want to ignore a channel, this adds a filter for that.  Does not hide the unwanted channels from the Channels tab, since they should still be accessible to the user if chosen.
This is based on the pull request #111, since I wanted to make sure there was a machine-generated translation of the filter description.
Related to #32.
> Add a filter to Public to allow for hiding of channels

- ui/ssb-msg.js
@KyleMaas I noticed that getting these messages ooo style in order to have the title show up properly was quite draining in the public view. So I'm inclined to just only to that for local messages.
> Don't try to pull thread titles from ooo

- ui/components.js
- ui/new-public-messages.js
- ui/public.js
Instead of figuring out autorefresh on the Public tab, this version does it the new-public-messages component.  The idea is that when a new message comes in, it checks to see if autorefresh is enabled and, if so, refreshes.  But then it blocks autorefreshing for 30 seconds.  At the end of that timer, it rechecks in case a message came in while it was blocked, and then it unblocks autorefreshing so the next message can refresh immediately.
The reason for the timer is because when you're doing a major sync operation it could otherwise trigger a whole bunch of refresh requests in a very short amount of time (it did this the first time I tried it).  So I think we still need a timer, but it needs to block instead of being the primary motivation for action.
So, does that look like an acceptable …
> Event-driven autorefresh on Public tab

- ui/helpers.js
- ui/private.js
- ui/ssb-profile-link.js
* Centralize "blank profile" image into helpers so it can be reused in multiple places without inline builds adding multiple copies of it.
* Add "blank profile" image to Private tab's Recipients list for people who don't have a profile image.
* Sort Recipients suggestions by name.
* Don't wipe out the people list in suggestions if no matches are found, also making it consistent with how recipientsOpen() works.
* Only update the component's people list once per method instead of modifying it (and possibly triggering hooks/processing) every time an element is pushed onto the array.
* Clean up a few stray tabs.
Fixes #131.
> Profile image placeholders on private

- npm-shrinkwrap.json
- package.json
Bump ssb-browser-core to 7.0.2 to get rid of unnecessary errors from chloride.
> Bump ssb-browser-core to 7.0.2

- messages.json
- ui/channel.js
- ui/onboarding-dialog.js
- ui/private.js
- ui/profile.js
- ui/public.js
Warn the user if their message goes over the 8192 byte limit, rather than just fail with a message on the console.
Fixes #130.
> Enforce message size limits

- README.md
Adds information to the README for how to add WebSockets support to ssb-room.  See #145.
(Going to try to upstream this as well, but at least for now it would be publicly documented.)
> Add info on ssb-room to README

- convert-to-inline.sh
- package.json
We now have several SVG files, JPEG files, and fonts.  This fixes the inline build so that they're included, which means themes still work in an inlined build.
Fixes #151.
> Fix inlining for new resource types

- messages.json
- net.js
- ui/connected.js
A bug crept into the Connected indicator with the internationalization stuff - it just flat out disappeared because I used the wrong syntax for the title attributes.  This fixes that and uses the SSB.connected() and new SSB.disconnected() functions to track the connection status instead of hooking the RPCs directly and effectively duplicating that functionality.  This also checks periodically to see if the feedSyncer is synced and uses a yellow indicator when it is connected but out of sync.
> Fix and improve Connected indicator

- css/main.css
This *should* fix https://github.com/arj03/ssb-browser-demo/pull/161#issuecomment-772825937
Tried it in both Chromium and Firefox.  It was previously broken in Firefox, and now works there.  Couldn't duplicate the problem in Chromium.  But in both browsers on my machine the emojis organize into two rows.
> Fix positioning bug in 'More Emoji' popup

- ui/markdown-editor.js
Fixes the mdEditor error mentioned in https://github.com/arj03/ssb-browser-demo/pull/170#issuecomment-773267088
Also fixes an issue where sometimes clicking suggestions did not work because the state change event would fire before the click and would hide the suggestions before the click could be processed.
> Fix mdEditor error

- browser.html
- css/main.css
- messages.json
- npm-shrinkwrap.json
- profile.js
- ui/browser.js
If you type an "@" in the upper right search box, it pops up a list of suggestions for profile names.  If you type in a profile name and hit enter or click one of the suggestions, it will take you to the corresponding profile.
Fixes #173.
> Go to profile by name

- ui/markdown.js
- ui/ssb-msg.js
- ui/ssb-profile-link.js
Requires this to properly function:
https://github.com/arj03/ssb-browser-core/pull/24
This change tries to display as many blobs as possible when not connected to a server (such as when Use Offline mode is active).  It also contains a workaround for profile images trying to load before the profile index is filled in.
Fixes #76.
> Load as many blobs as possible when offline

- ui/ssb-msg.js
Evidently the second emoji in the list became the thumbs-down emoji instead of the Vulcan salute emoji.  This changes that back.
Must have happened during the transition to the popup menu.  Those emojis don't show up in vim for me.
> Change out thumbs-down emoji

- browser.html
- css/main.css
- ui/profile.js
Try and make a bit more space in the upper menu by converting Profile and Connections to icons like we did for the lower menu.  Also move the indicators so they don't take up so much space.
Fixes #92.
> Convert upper Connections and Profile tabs to icons

- messages.json
- ui/connections.js
When connecting to a room-endpoint, ask the user if they also want to follow the profile at the other end.
Fixes #64.
> Ask if the user wants to follow room endpoints

- browser.html
- css/thread.css
- messages.json
- npm-shrinkwrap.json
- ui/thread.js
When replying to a thread, show which participants in the thread are blocking you and will not see your reply.
Gotta be honest, I couldn't really test this one.  I tried various combinations of simulating being blocked, but I didn't have a great data set to be able to confirm that I could see a thread with someone who was blocking me and that this would show that.  I'm hoping this can be tested, but at this point I'm not sure either one of us are actually controversial enough with our posts to be blocked by someone where we would otherwise see their posts.
Fixes #205.
> Show thread participants blocking you when you reply

- npm-shrinkwrap.json
> This seems to have broken my local build. It can't find ssb-blob-files anymore. Have to look at this another time.
From @arj03 at https://github.com/arj03/ssb-browser-demo/pull/226#issuecomment-778586267
I was able to duplicate this when not using my local ssb-browser-core branch I had updated dependencies on.  Since it was a dependency issue, I rebuilt npm-shrinkwrap.json with the dependency updates, and it fixed the build process.  It also eliminated the warning about package vulnerabilities.  And, in test running it, it seems to work fine with the dependency updates as far as I can tell.
> Rebuild npm-shrinkwrap to fix the build process

- npm-shrinkwrap.json
- package.json
In efforts to help with #219, this deduplicates pull-stream from a few packages which haven't been updated in several years.
This shrinks the release bundle from 4375827 bytes to 4358267 bytes, a savings of 17560 bytes.
> Dedupe pull-stream

- package.json
More work on #219.  Patches out Highlight.js.  Takes release bundle down to 3558556 bytes - savings of 799711 bytes.
> Patch out Highlight.js

- npm-shrinkwrap.json
- package.json
Turns out we were using ssb-keys, but only as a dependency of other stuff.  In the case of it not being able to be deduplicated, npm could end up installing it only under the other packages requiring it, which caused a dependency error for ssb-browser-demo.  This fixes that by pulling it in directly.
> Fix missing dependency on ssb-keys

- dedupe.sh
- npm-shrinkwrap.json
- package.json
Takes release bundle from 3559975 bytes to 3514373 bytes - a savings of 45602 bytes.  Diminishing returns, but it's still something.  This also splits out the dedupe patching into a shell script which runs postinstall instead of trying to inline it all.
> Dedupe more

- messages.json
- ui/connections.js
Adds information to the connections list to show when a connection last received an update.
Interestingly, this also allows you to see how long it takes for the receive queue to flush to the database and be indexed, since if you pull a large batch of data (follow someone with a lot of followers you don't already replicate), you can see the last updated change quickly and then watch the profiles fill in on the progress bar as they complete indexing.
Fixes #141.
> Add last updated information to connections

- ui/browser.js
Evidently the profile search (type "@" and then something in the search bar, hit Enter) was broken because of the transition from the profiles index to aboutSelf.  This fixes that.
> Fix profile search

- browser.html
- click-catcher.js
- css/main.css
- npm-shrinkwrap.json
- package.json
- ssb-singleton.js
- ui/browser.js
- ui/channel.js
- ui/channels.js
- ui/components.js
- ui/connected.js
- ui/connections.js
- ui/group.js
- ui/groups.js
- ui/helpers.js
- ui/link-contextmenu.js
- ui/markdown-editor.js
- ui/markdown.js
- ui/new-private-messages.js
- ui/new-public-messages.js
- ui/notifications.js
- ui/private.js
- ui/profile.js
- ui/public.js
- ui/search.js
- ui/ssb-msg.js
- ui/ssb-profile-link.js
- ui/thread.js
- window-controller.js
Basic protection against concurrency issues. See #139. Uses a localStorage-based mutex which times out in case a tab dies on us. Adds a bunch of extra checks throughout the codebase to try to gracefully handle a locked SSB.
Also fixes:
* Fix error where clicking Refresh when you didn't have any messages would error out.
* Fix missing getProfileNameAsync in Private.
> Basic protection against concurrency issues

- browser.html
- click-catcher.js
- css/main.css
- ui/browser.js
- ui/common-contextmenu.js
- ui/components.js
- ui/ssb-msg.js
- ui/view-source.js
Adds a context menu (right-click) for ssb-msg so you can right-click a message and choose one of the following options:
* View whole thread
* Open thread in new tab
* Copy message ID
* Copy thread root ID
* View source
Fixes #263.
> Message context menu

- ui/ssb-msg.js
- ui/thread.js
I was not able to duplicate the problem in #271, but looking at the code, it makes sense how it could happen.  This makes it so the user has immediate feedback of their posting once it's been added to the database.  It also fixes a few bugs relating to null message keys - there was already code there for that case, so I have to assume something else was able to trigger that before, but it wasn't fully working.
Fixes #271.
> Make sure replying to a Thread shows feedback of the posting

- package.json
- ui/components.js
- ui/connections.js
- ui/dht-invite.js
(Needs to be used in conjunction with the add-dht-support branch of ssb-browser-core.)
Figured I'd pick this back up again now that @staltz integrated my Hyperswarm changes into multiserver-dht version 5.0.0.  As evidenced by https://github.com/arj03/ssb-browser-core/issues/43, rooms as they currently are are not terribly intuitive until you understand how they're supposed to work, and it would be awfully nice if we had DHT support for connecting without having to use more centralized infrastructure like Rooms 2.0.
This has been updated to use public versions (not based on my repos) of the DHT stuff with only a couple minor patches.  This is runnable as-is and does seem to function, although there is one error that gets logged that I don't quite understand:
```
method:tunnel,ping is not …
```
> Add DHT support

- ui/profile.js
So...in trying to fix #305, it turns out that we were already checking if the description was undefined, and `self` was already set to `this`.  There were no code paths I could find which would result in `this.descriptionText` to actually be `undefined`.  But it was possible for the error to show up if a profile's description was something other than a string where `matchAll` was not defined on it.  So under the premise that that's probably actually what was causing that error, this changes the `this` reference to `self` for consistency and adds a check to ensure that the description is actually a string before trying to run the regular expression on it.
Fixes #305
> Fix issue where profile description could cause an error

- messages.json
- ui/ssb-msg.js
Quick note: I included the colon on the end in the translation itself, since Japanese uses a different (fixed-width) character for colons than English and Portuguese.
Fixes #308
> Fix missing "Mentions:" translations

- ui/ssb-msg.js
For OOO messages, we don't have author or timestamp information.  A user also should not be able to react to messages when we have no information about the message other than its ID and the fact that it exists somewhere.
Fixes #295
> Don't try to display information we don't have when displaying an OOO message

- messages.json
- ui/thread.js
Previously, if you were offline and tried to load a thread with a root you didn't have, it would just freeze.
This makes it so that it displays a useful message to the user and gives them a button to try fetching it again, in case the connection being down was only a temporary thing.
Fixes #264
> When we can't fetch a thread, display an error

- ui/new-private-messages.js
- ui/new-public-messages.js
When you post a new message, it's pretty obvious there will be a new message.  There's no need to show the new message indicators and cause the user to click them and refresh to see what they are, only to find out it was just their own message.
Fixes #302
> Fix issue where posting a new message popped up the new message indicators
