arj03/ssb-browser-demo

simple-blobs.js
I was going to increase this to 10 seconds, but thought that 2 seconds should probably be fine. :upside_down_face:
=> Change blob timeout to 2 seconds

start-server.sh
Adds an easy server starting script which can be run as a regular (non-root) user.
=> Easy server starting script

ui/connected.js
Fix for #16 - changes the connection icon from a unicorn to a green fisheye.
=> Change connection icon to a green Unicode fisheye

README.md, npm-shrinkwrap.json, package.json
Builds a file in the dist directory called index-inlined.html which contains all needed assets to run ssb-browser-demo without any further requests to the server.  Basically consolidates the entire program into one easy-to-download, easy-to-host, easy-to-distribute HTML file.
=> Inline the built files into a single HTML file for easy distribution

ui/public.js
To help debug an issue I'm having likely due to a corrupted database.
=> Add error handling to Public tab

browser.html, css/main.css, ui/browser.js, ui/channels.js
Pretty self-explanatory.  Adds a tab to the top of the page called Channels which displays a clickable list of the available channels.
=> Add a Channels tab to show available channels

browser.html, css/main.css, css/theme-dark.css, defaultprefs.json, localprefs.js, npm-shrinkwrap.json, package.json, ui/browser.js, ui/settings.js
This is based on my "settings" branch, and as such includes changes within that pull request.
This one adds support for color themes, and includes a dark color theme.
=> Settings - themes

css/public.css, ui/public.js
Allow for posting messages on the Public tab with a channel attached.  Fixes #62.
=> Public message with channel

browser.html, localprefs.js, messages.json, npm-shrinkwrap.json, package.json, ui/browser.js, ui/channel.js, ui/channels.js, ui/connected.js, ui/connections.js, ui/notifications.js, ui/onboarding-dialog.js, ui/private.js, ui/profile.js, ui/public.js, ui/settings.js, ui/ssb-msg-preview.js, ui/thread.js
Add proper page titles so they show up meaningfully in browser history.  Based off of the localization feature (#88).#88 
Fixes #65.
=> Add page titles for history

browser.html, localprefs.js, messages.json, npm-shrinkwrap.json, package.json, ui/browser.js, ui/channel.js, ui/channels.js, ui/connected.js, ui/connections.js, ui/notifications.js, ui/onboarding-dialog.js, ui/private.js, ui/profile.js, ui/public.js, ui/settings.js, ui/ssb-msg-preview.js, ui/thread.js
* Adds support for internationalization based on the browser's locale, if available.
* Moves strings to an internationalization dictionary in messages.json.
* Adds a UK English translation.
* Adds a setting to override the browser's locale under Settings.
=> Add support for internationalization

messages.json, ui/helpers.js, ui/thread.js
Displays a thread title, if there is one, on the Thread page.  See #67.
=> Show thread title on thread page, if applicable

ui/connections.js
Adds friendly names for existing connections in the Connections screen.
=> Add friendly names for existing connections

css/modal.css
Fix problems with light text on light backgrounds in themes which use light text as their default.  Fixes #102.
=> Fix problems with popups in themes

css/profile.css, ui/profile.js
* Make the "self" profile layout more similar to the "others" layout.
* Use space a little more effectively to put more information closer to the top of the page and above the fold.
Fixes #107.
=> Move profile page information around

messages.json
* Fix a couple typos in the base English translation.
* Add Japanese translation based mostly on machine translation with some minor tweaks from my not-even-N5 level of Japanese proficiency.
* Add Pirate translation, per https://github.com/arj03/ssb-browser-demo/issues/103#issuecomment-766156259
=> Add translations

defaultprefs.json
Disables autorefresh by default unless specifically enabled under Settings.
=> Disable autorefresh by default

net.js, npm-shrinkwrap.json, package.json, profile.js, ui/browser.js, ui/helpers.js, ui/private.js, ui/profile.js, ui/ssb-msg.js, ui/ssb-profile-link.js, ui/thread.js
Continuation of https://github.com/arj03/ssb-browser-demo/pull/121
=> Ssb about suggest

messages.json, ui/channel.js, ui/public.js
Validates that the message field is not empty when trying to post on both Public and Channel.
Fixes #127.
=> Make sure there's a message before trying to post it

messages.json, ui/thread.js
Changes the Thread view's reply area to a Markdown editor, just like Public, Private, and Channel.
Fixes #138.
=> Add Markdown editor to Thread view

package.json, ui/notifications.js
Attempted to do this using pull-stream.  I think it seems to work okay, although I'm also not an active enough poster to really give this a good test.
=> Include replies in Notifications

ui/channel.js, ui/components.js, ui/markdown-editor.js, ui/onboarding-dialog.js, ui/private.js, ui/profile.js, ui/public.js, ui/thread.js
Refactor of the Markdown editor and associated blob adding functionality into its own component.
=> Refactor Markdown editor into its own component

ui/markdown-editor.js
Cherry picked just the two commits for profiles from #147.  We can always reintroduce commit 351b4c5 to bring channels back in later.
=> Suggestions for profiles only

css/main.css, css/profile.css, ui/profile.js, ui/ssb-profile-link.js
Implements blurring idea from @cinnamon-bun at https://github.com/ssbc/patchwork/issues/1077 along with obscuring the profile images.
Fixes #167.
=> Blocked profiles

browser.html, css/channels.css, css/groups.css, css/main.css, messages.json, ui/browser.js, ui/channels.js, ui/groups.js
Implement suggestions from:
https://github.com/arj03/ssb-browser-demo/pull/166#issuecomment-773583848
* This cherry-picks the "Css tweak for groups" commit, but moves the CSS to a new "groups.css" file.
* Notifications is now a bell emoji and is placed next to the Settings gear in the tab menu.
* User groups have now been moved to their own tab.
=> User groups improvements

README.md
Add information to the README on how to translate to other languages.
See #103.
=> How to translate

ui/profile.js
Fixes #179.  Turns out it didn't need a full refresh.  Just the local version of blocking status needed to be updated.
=> When blocking or unblocking, update the Profile page

browser.html, css/main.css, ui/browser.js
Tweaks to the search box and main menu to try (as much as possible) to make sure they stay on the same line.  Clicking into the search box how expands it.
=> Fix main menu positioning

css/main.css
=> Tweak the search box

css/groups.css, messages.json, ui/group.js, ui/groups.js, usergroups.js
Implement suggestions from #200.
Fixes #200.
=> Group tweaks

browser.html, css/main.css, css/profile.css, css/theme-dark.css, css/theme-floralgardenbird.css, css/theme-pirateship.css
See how this works.  It changes the size of the avatar images on Profile and rearranges the bottom menu (I didn't even know that was being used).
See #202.
=> Mobile tweaks

browser.html, css/main.css, css/profile.css, ui/profile.js
This fixes the profile link at the bottom.  Turns out it was due to this:
[Prop Casing (camelCase vs kebab-case)](https://vuejs.org/v2/guide/components-props.html#Prop-Casing-camelCase-vs-kebab-case)
It also makes it so that it updates when you save your profile.
Still can't find a way to duplicate the Profile editor not working, though.
=> Mobile Tweaks 2, Electric Boogaloo

npm-shrinkwrap.json, package.json, ui/browser.js, ui/channels.js, ui/markdown-editor.js, ui/public.js
Use the new channel index.  Draft for now until we figure out if this is a good way to do this.
=> Channel index

css/profile.css
See https://github.com/arj03/ssb-browser-demo/pull/207#issuecomment-774744610
=> Remove underline from follow status lines

css/main.css
=> Unsquish Public and Private indicators

localprefs.js, messages.json, ui/public.js
One more step toward completing #32.  This ended up being more complicated than I expected due to group queries (including membership queries) being asynchronous.  This required the message queries to become asynchronous as well.
=> Groups filter for Public

ui/browser.js
While trying to track down an issue, I ran into a problem where I was getting connection errors but couldn't trace why.  This makes it so that connection errors are logged.
=> Log connection errors

css/main.css, messages.json, ui/profile.js, ui/public.js, ui/ssb-msg.js, ui/thread.js
When someone has updated their profile, show what they changed.
Fixes #229.
=> Show profile changes

package.json
=> Eliminate pushd and popd from cleanup script

ui/ssb-msg.js
Adds support for "blog" messages.  Theoretically, they should be UTF-16, but in reality when I tried decoding existing messages as UTF-16, it came out as garbage.  So this decodes them as UTF-8, which is how most of the messages I found were actually encoded.
Fixes #223.
=> Add support for blog-type messages

ui/profile.js
If you refresh the page while looking at a profile, previously it would attempt to load the profile immediately before the index loaded, resulting in an empty result.  This changes that so that if the index isn't loaded, it waits several seconds to let the index load and then tries again.  If that doesn't work, it waits for a connection with data to load the profile.
Fixes #51.
=> Retry loading profile after refresh

messages.json, ui/browser.js, ui/new-public-messages.js, ui/threads.js
Adds both manual and automatic refresh for Threads.
=> Add refresh options for Threads

css/main.css, ui/ssb-msg.js
Turns other peoples' post reactions into clickable links which take you to their profile.
Fixes #273.
=> Add ability to click existing reactions to see their profile

ui/helpers.js, ui/threads.js
Adds tooltips for the Threads page to show a preview of the first and the latest message in each thread.
Fixes #275.
=> Add thread tooltips

ui/new-private-messages.js, ui/new-public-messages.js
=> Fix minor SSB bug for really slow situations

messages.json
=> Add pt-BR translations

messages.json
I was comparing the Portuguese version with the English messages and here goes some suggestions, by the way I tried to keep gender-neutral.
cc @luandro
=> Portuguese review

npm-shrinkwrap.json, package.json, ui/channel.js, ui/channels.js, ui/group.js, ui/groups.js, ui/new-private-messages.js, ui/new-public-messages.js, ui/notifications.js, ui/private.js, ui/profile.js, ui/public.js, ui/search.js, ui/ssb-msg.js, ui/thread.js
Should be ready to go now.
Depends on https://github.com/arj03/ssb-browser-core/pull/50
=> Bump browser core and use where() from db2 2.0

messages.json, npm-shrinkwrap.json, ui/thread.js, ui/threads.js
Show a loading message when waiting for results from a message search on the Thread and Threads pages.
Fixes #292
=> Show loading message

browser.html, css/main.css, npm-shrinkwrap.json, package.json, ui/markdown-editor.js, ui/private.js, ui/public.js
This partially works.  Problems so far include:
* ~Clicking a suggestion in a popup suggestion box (like for channels or people) does not work on the first try.  Subsequent suggestion clicks do seem to work.~
* ~Adding images does not work properly.~
Fixes #298
=> Update ToastUI-Vue editor 3.0.0

messages.json, ui/browser.js
Validate message and feed IDs before trying to blindly navigate to them.
Fixes #270
=> Check message ID and profile ID validity before trying to navigate

browser.html, css/main.css, messages.json, npm-shrinkwrap.json, package.json, ui/components.js, ui/onboarding-dialog.js
Allow the user to choose to onboard as a new user or go straight to loading from a mnemonic key.
Fixes #255
=> Add mnemonic key recovery to onboarding

ui/helpers.js
=> Add fix and diagnostic message for goofy title crash
